/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 1.2 */
/* Thu Jul 14 14:31:02 2022 */

/* parameterized module instance */
pwrguard __ (.D( ), .E( ), .Q( ));
